services:

  # Set bind-mounted folder ownership
  permissions:
    image: docker.io/overhangio/openedx-permissions:21.0.0
    restart: on-failure
    entrypoint: []
    command: ["sh", "/usr/local/bin/setowners.sh"]
    environment:
      OPENEDX_USER_ID: "1000"
    volumes:
      # Command script
      - ../apps/permissions/setowners.sh:/usr/local/bin/setowners.sh:ro
      # Bind-mounted volumes to set ownership
      - ../../data/lms:/mounts/lms
      - ../../data/cms:/mounts/cms
      - ../../data/openedx-media:/mounts/openedx
      - ../../data/openedx-media-private:/mounts/openedx-private
      
      
      
      
      

  ############# External services

  

  

  

  

  smtp:
    image: docker.io/devture/exim-relay:4.96-r1-0
    restart: unless-stopped
    user: "100:101"
    environment:
      HOSTNAME: "lms.biolnks.io"

  ############# LMS and CMS

  lms:
    image: docker.io/overhangio/openedx:21.0.0-indigo
    environment:
      SERVICE_VARIANT: lms
      DJANGO_SETTINGS_MODULE: lms.envs.tutor.production
      UWSGI_WORKERS: 2
    restart: unless-stopped
    volumes:
      - ../apps/openedx/settings/lms:/openedx/edx-platform/lms/envs/tutor:ro
      - ../apps/openedx/settings/cms:/openedx/edx-platform/cms/envs/tutor:ro
      - ../apps/openedx/config:/openedx/config:ro
      - ../apps/openedx/uwsgi.ini:/openedx/uwsgi.ini:ro
      - ../../data/lms:/openedx/data
      - ../../data/openedx-media:/openedx/media
      - ../../data/openedx-media-private:/openedx/media-private
    depends_on:
      - permissions
      
      
      
      
      - smtp
      

  cms:
    image: docker.io/overhangio/openedx:21.0.0-indigo
    environment:
      SERVICE_VARIANT: cms
      DJANGO_SETTINGS_MODULE: cms.envs.tutor.production
      UWSGI_WORKERS: 2
    restart: unless-stopped
    volumes:
      - ../apps/openedx/settings/lms:/openedx/edx-platform/lms/envs/tutor:ro
      - ../apps/openedx/settings/cms:/openedx/edx-platform/cms/envs/tutor:ro
      - ../apps/openedx/config:/openedx/config:ro
      - ../apps/openedx/uwsgi.ini:/openedx/uwsgi.ini:ro
      - ../../data/cms:/openedx/data
      - ../../data/openedx-media:/openedx/media
      - ../../data/openedx-media-private:/openedx/media-private
    depends_on:
      - permissions
      - lms
      
      
      
      
      - smtp
      

  # MFE
  mfe:
      image: docker.io/overhangio/openedx-mfe:21.0.0-indigo
      restart: unless-stopped
      volumes:
          - ../plugins/mfe/apps/mfe/Caddyfile:/etc/caddy/Caddyfile:ro
      
      depends_on:
          - lms