CMS_HOST: cms.biolnks.io
CMS_OAUTH2_SECRET: uDdWEmndDC9zhhhPsWtpl92M
CONTACT_EMAIL: adeel.octaloop@gmail.com
ELASTICSEARCH_HOST: 10.0.5.90
ELASTICSEARCH_PORT: 9200
ELASTICSEARCH_SCHEME: http
ENABLE_HTTPS: true
ENABLE_WEB_PROXY: false
ID: nqJaVGI5pYOquijVA9rQhPMX
JWT_RSA_PRIVATE_KEY: '-----BEGIN RSA PRIVATE KEY-----

  MIIEowIBAAKCAQEAxFN/VjzdDLZ+epAPa8c28R8xe/hWcgTlnrNuf46K9zejd6LZ

  KgFl5Owbe/ClxWRkyAcHRFQrQG419ZsIEFJtXAsDnfBP5dKEON+d/tO+DmUYIz/O

  pQ5uW0jfZnqDaQe2epKY5gg5Zrt6pmWTC4f0mRxmLvNLYqXr5xVnp05wRyPWAv/U

  B0fQaEQ1vX2vNpGNPuKqY98MvHa8zazp2rOM1JVKa3Q0uUPxfB2QDatOVB+K2B6B

  /cJXigMQ+9xuLbpRk2xptF70Bze79ZQgIQ7vtU/fwdXd7sUJqqt0FrLgpofzN8vJ

  pbQUiXCN2TpDnjIdjdY0vqtu1GHmFO9qOoB6OQIDAQABAoIBAADA//8ucqbcLeDT

  RsviKErav3o7ZObr2o82dIPW4fUQaKH1T8zX091XhBoraBI5pXgYgXr4sRspO9nP

  7kL/HgkOyG/F1CNiIJHbV0763y2iTmpsPKM+SpwydnEn9/M3orLBIgctcZL8a1HS

  QrNLorEn08NLDzdiGGV7G+UflFIhm7WD/zdlS6VpKviMbdWrqOgCUZudk/+lsrKT

  eQzcqkIA3bzH2HSNWqicSHjk3jv+M4LVGKzfN9ujWxiAAGx+x337Otra4wV9PIMk

  TK1lXpNB08JJz+wYmQ0KTThskwyZJpzNMAPpCHxN5pu+PGstqmNGyCbD8wNhe4TN

  SL0Jt4ECgYEA2m7SkbEF0RE2tmBuSC5VY2mts2+YlUa53NGDFQTkv2yaL1pUKRCM

  7lFr+/+Fv6ALgKBY61MFxZ1eCEdSUZvy6u8uUE2Z911wccQ6yP6xqOh8UpWb3hV6

  vunmzjXz6nbOYLDYrxoTLTUTVNU/VQTHNOiBSN7k9erniDPM/hLb5HECgYEA5hdb

  pUkxAFEjfPB9Nhq4Wv8F4lZqzQQeLVqXZJm+EOE+Kq834TWfvbFdZ3Tg7yQ1GGy6

  OMamIHstReKN6zzN2y/iYIU1r0+pcyzLHR+arZR4UxLkrYwhdCYhoLtRTHlwdROH

  dwNFoSMlBoRO24dcbkypQRpVG6uaAK8m9X2ktkkCgYAzGC1FSyVTLDWiH5hsZfov

  UO8CxB3q/SpIzvFcn1JqvJqsbPK20FpG/ODHh5PfqS5HnjpugXMeMJtoUFafJF2E

  OwKYYi6bwE2nLwGZNoqUOh2qq7hUEK4vrkMBBXnS5IuN7pAhFXZa4sls1J0F5CI8

  7A4h35GrPJGAOK3A2OR64QKBgQDSGpow//ii1XSWbfOoKBYX4a+50jeMJip4N7Tu

  xATu3P8rcvyPxausR/2Grw+Gz4U8XGxf0+V224OnwQzetZM0hzEr+fffsdqFtW1z

  lpxjzKNjGGmAn+kcaoVihCnkry+leMPGRVKbpb/1h3OKurwIbDBRpn342mWyIj5t

  BOIXIQKBgFMLLa5U2CYR2v6QYpRKY9SSWeHt9xrF+RzBxUTwOC8PvSQCuU1VEBA2

  fQBWW87vUGBuq2Of7h/LjtMYRGiK+ltF8OhvHhLDdMNdKf8C59G2nhTudBUW1EEq

  Ik8ivgxafVj6uqZmVku1xbaqnd+g6TCwVrtFPtGOH9TQn6yU0XjV

  -----END RSA PRIVATE KEY-----'
K8S_MEDIA_VOLUME_SIZE: 50Gi
K8S_STORAGE_CLASS: gp2
LANGUAGE_CODE: en
LMS_HOST: lms.biolnks.io
LMS_MFE_APP_URL: https://apps.lms.biolnks.io
MEILISEARCH_API_KEY: 889ab193cdfeef4d81f80e6b239557aa7af5d366c2d5a9862973a220ce32087e
MEILISEARCH_API_KEY_UID: f5a1df06-6256-4b12-ae32-8affe3d3ddfb
MEILISEARCH_HOST: 10.0.5.90
MEILISEARCH_MASTER_KEY: password123
MEILISEARCH_PORT: 7700
MEMCACHED_HOST: memcached
MFE_HOST: apps.lms.biolnks.io
MONGODB_DATABASE: openedx
MONGODB_HOST: 10.0.5.90
MONGODB_PASSWORD: password123
MONGODB_PORT: 27017
MONGODB_USERNAME: admin
MYSQL_HOST: openedx-mysql.cc58y04quww7.us-east-1.rds.amazonaws.com
MYSQL_PORT: 3306
MYSQL_ROOT_PASSWORD: OpenEdXStrongPass123!
MYSQL_ROOT_USERNAME: admin
OPENEDX_MYSQL_DATABASE: openedx
OPENEDX_MYSQL_PASSWORD: OpenEdXStrongPass123!
OPENEDX_MYSQL_USERNAME: admin
OPENEDX_NUM_PROXIES: 2
OPENEDX_SECRET_KEY: vFfopWzSgDwH1wbJAL66wS7m
PLATFORM_NAME: Adeel OpenEdX
PLUGINS:
- mfe
- indigo
PLUGIN_INDEXES:
- https://overhang.io/tutor/main
- https://overhang.io/tutor/contrib
REDIS_HOST: redis
REDIS_PASSWORD: ''
REDIS_PORT: 6379
RUN_ELASTICSEARCH: false
RUN_MEILISEARCH: false
RUN_MONGODB: false
RUN_MYSQL: false
RUN_REDIS: false
