CMS_HOST: cms.biolnks.io
CMS_OAUTH2_SECRET: IyGFgxP9y4YaP43JLtV1IlH8
CONTACT_EMAIL: contact@lms.biolnks.io
ELASTICSEARCH_HOST: elasticsearch.default.svc.cluster.local
ELASTICSEARCH_PORT: 9200
ENABLE_HTTPS: false
ENABLE_WEB_PROXY: false
ID: qCk7AcegGnvNITs9udpJxsnS
JWT_RSA_PRIVATE_KEY: '-----BEGIN RSA PRIVATE KEY-----

  MIIEowIBAAKCAQEA3kc8Ja2myncgxkapHVqDs8jHsLGxJkRBgtWrjq/isuY0ysor

  NTMUxy7FgDm63GrzcZccrGb7jH4/wCbwRoR9UOrgQ1Unh9W91D4r/6jSasK1vZTE

  X9F0pfIv1PEzqAZb4C0vYecyEOxdc9KVavnlGwCEk1k+xrVajuplnXZ4FolO3D7b

  4pN1FaeGr0OOWkYFz2v6H7KEZhtjsETpcS2rTrSttpY6MLuf1dzVgYWycaOtJ0g9

  uHILkaQwqZhNgFat6sXHm6gQN5MESrUOTV9pg80PPLTCq/1TLQOmbroA1Fi0wth2

  7+aNeJVw9AcXrht9iFMLu6MINl7+GDDmpYoGgwIDAQABAoIBAExHMdLURrqQKwUf

  1oUmPLADpNN0BxDUt46IeLkcjrVJ3rAAtNcq0mSQHmKkbQWbBjPi4YogRQ6vfH0a

  X7YzXTXZhGBW5pvss5oUQ9EWRC8y5l9KoCEppdgUxmlS5KEynXDO0MXOKxY3ptJK

  X9A4NXEQum4+YBacwZjtwzVIJGnGzQJOZpG9Pxx8yFd8p++p0tWxtnAu9WcgcvMK

  Q70LSragas/Y+4JkkG+/5q+MGTMsR8QXtzEnxPh/x2wgpvIpok32weEqFwEXOXxx

  KcF99HOiBfFTyVoV9cZJowfXRzxJ4Jmp8h0me7VnbNIzgVC5RzEwEuiXjLXAUUAA

  GkRmQWECgYEA4ofFroGlN2/iJQeB/e+KVGDEUTJWIoEwE5BsVGPQKxSWEXBGa8GF

  jlGI+0yPVciaaQWqowBeeYPds7JlQ4oT+XmvDt4jFvPt7RbICk8HVgrT7BXs8PLQ

  JyaiSmHbNMZjvFea7YGdNBGXuPE+JdD80e2iFwOUaQcOqoOwEEt2HfsCgYEA+zHa

  fZScXaLnXHYvEtZ8YEcyHoNZFgm7pAtjfVDDPlJC1kdQ1pGhzxVF0uHzJLu7lDd6

  AcrHZSgm+E+kpnGk16ReI6vsAlto3m3VlmRiEiJSVop/TYZHvbjwLSivumqCbRkk

  IgRCjibTE3zT+AfYHta7kErA/7JLt2dpbmAU+xkCgYBzoLH6vRpEDcv08rwbjiWh

  pDMQ7wygWCjeE534BWrAUqW3CQQpBILTfjLZct7G/royWT4cLZgLlo+XpbuimdxQ

  PxhoEmL+2Evd9P7upCAufyBlJVvoMUimc0Xrib+GVK2b+WuPR9WiOkijkiAS1XX3

  AcD21lDuuzd1OfqolpwX+QKBgCMnswBoUAn6xo52K9hjFD0VObpzf4BKFGy8+0uK

  hgiu0pPSn0moUBD/VSpSXQkDDRmNOhIOIyHRIMMXwl9ZAEz9v/8WDI235VFb5cyK

  d/85tnROJcrfxCKVQ2fOjel1BpPmNNxd5EKoxFmx2qiX0HNgchebnq8qcNZWLrc3

  0zfhAoGBAJoQum2hO25Fx0nNX8sKjIzSbPD24GAupCz3bCU2pjQUUBCOVkTtC/Be

  kBNFDSZgl/0H1/nTB8z4buIzEq0W44dDkwRi21/UgopJ9UF8iggkypk9MrNwNI2T

  TaTjEOXhFJ5NDal1S9TwenEnATyiRo59JpMb9rkgX+7/ypV4hCGJ

  -----END RSA PRIVATE KEY-----'
LANGUAGE_CODE: en
LMS_HOST: lms.biolnks.io
MEILISEARCH_API_KEY: eb5de10bd66ce7a53aba61ce9ac041fd3b3fc3545623909c191f3a799c923347
MEILISEARCH_API_KEY_UID: 9d53c798-24e1-47c6-baad-6677d4b70784
MEILISEARCH_MASTER_KEY: HqVdcAHwN3X2FRjqcRXmGwTc
MONGODB_HOST: mongodb.default.svc.cluster.local
MONGODB_PORT: 27017
MYSQL_HOST: openedx-mysql.cc58y04quww7.us-east-1.rds.amazonaws.com
MYSQL_PORT: 3306
MYSQL_ROOT_PASSWORD: OpenEdXStrongPass123!
MYSQL_ROOT_USER: admin
MYSQL_ROOT_USERNAME: admin
OPENEDX_MYSQL_PASSWORD: OpenEdXStrongPass123!
OPENEDX_SECRET_KEY: vIIPdxtkbFFUupjQo1pC6HHm
PLATFORM_NAME: My Open edX
PLUGINS:
- indigo
- mfe
PLUGIN_INDEXES:
- https://overhang.io/tutor/main
- https://overhang.io/tutor/contrib
REDIS_HOST: master.openedx-redis.8lgphg.use1.cache.amazonaws.com
REDIS_PORT: 6379
RUN_ELASTICSEARCH: false
RUN_MONGODB: false
RUN_MYSQL: false
RUN_REDIS: false
